<a href="https://colab.research.google.com/github/Mohan9392/REJOLT-DATASCIENCE/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[3,7,5],[8,4,3],[2,4,9]])

In [ ]:
print(np.amin(a,axis=1))

[3 3 2]


In [ ]:
print(np.amin(a,axis=0))

[2 4 3]


In [ ]:
print(np.amax(a,axis=0))

[8 7 9]


In [ ]:
print(np.amax(a,axis=1))

[7 8 9]


In [ ]:
print(np.ptp(a))

7


In [ ]:
print(np.ptp(a,axis=1))

[4 5 7]


In [ ]:
print(np.ptp(a,axis=0))

[6 3 6]


In [ ]:
a=np.array([[30,65,70],[80,95,10],[50,90,60]])

In [ ]:
print(np.median(a))

65.0


In [ ]:
print(np.median(a,axis=0))

[50. 90. 60.]


In [ ]:
print(np.median(a,axis=1))

[65. 80. 60.]


In [ ]:
a=np.array([[3,7,5],[8,4,3],[2,4,9]])


In [ ]:
print(np.mean(a))

5.0


In [ ]:
print(np.mean(a,axis=0))

[4.33333333 5.         5.66666667]


In [ ]:
print(np.mean(a,axis=1))

[5. 5. 5.]


In [ ]:
a=np.array([1,2,3,4])

In [ ]:
print(np.average(a))

2.5


In [ ]:
wts=np.array([4,3,2,1])

In [ ]:
print(np.average(a,weights=wts))

2.0


In [ ]:
print(np.mean(a))

2.5


In [ ]:
print(np.std([1,2,3,4]))

1.118033988749895


In [ ]:
print(np.var([1,2,3,4]))

1.25


In [ ]:
print(np.var(a))

1.25


In [ ]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])

In [ ]:
b=np.array([1.0,2.0,3.0])

In [ ]:
print(a)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


In [ ]:
print(b)

[1. 2. 3.]


In [ ]:
print(a+b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
